# Generated by Django 4.0.4 on 2022-05-14 17:43

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='users',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=75, unique=True, verbose_name='Usuario')),
                ('dirreccion', models.TextField(null=True, verbose_name='Direccion de usuario')),
            ],
            options={
                'verbose_name': 'usuario',
                'verbose_name_plural': 'Usuarios',
            },
        ),
    ]
