# Generated by Django 4.0.4 on 2022-05-14 18:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_juguete'),
    ]

    operations = [
        migrations.AlterField(
            model_name='juguete',
            name='compra',
            field=models.DateField(auto_now_add=True, verbose_name='fecha de compra'),
        ),
    ]
